################################################################################
# Options
################################################################################

legacy_layout=0

# Hide by default
no_display

# [top/bottom/center]-[top/bottom/center]
position=top-center

# int
# fps_limit=

# OPTIONS:
# - 0 = adaptive
# - 1 = off
# - 2 = mailbox
# - 3 = on
vsync=0

################################################################################
# Keybinds
################################################################################

toggle_hud=Shift_R+F12

################################################################################
# Layout
################################################################################

gpu_stats
gpu_temp

cpu_stats
cpu_temp

ram
vram

fps
frametime

# graphs=cpu_load,gpu_load

frame_timing

################################################################################
# Styling
################################################################################

# --- Colors ---

text_color=c8c5d1
background_color=190707

gpu_color=d94f6e
cpu_color=eb6c6c

vram_color=ab6670
ram_color=ab6670

engine_color=d94f6e

frametime_color=d94f6e

io_color=d3a891

# --- Other ---

round_corners=8
background_alpha=0.5

font_size=20
font_file=/usr/share/fonts/TTF/JetBrainsMono-Bold.ttf
