# ==============================================================================
# hutao-laptop — Lenovo IdeaPad 1 15AMN7
# ==============================================================================
# Ryzen 3 7320U "Mendocino", Radeon 610M, 8GB soldered LPDDR5, NVMe.
#
# Only genuinely hardware-specific settings belong here. The bootloader, the
# kernel pin, the graphics stack, users and secrets are all in hosts/common —
# shared with hutao-desktop when it lands, so the two cannot drift.
#
# Known hardware note: this model (82VG/82X5) was one of nine Lenovo AMD
# laptops hit by NVMe IOMMU page faults on suspend/resume, fixed by DMI quirks
# in Linux 6.6. Unstable is far past that. If suspend ever misbehaves, start
# there rather than blaming NixOS.
_: {
  imports = [
    ../common
    ./disko.nix
    ./hardware-configuration.nix
  ];

  networking.hostName = "hutao-laptop";

  # Early KMS: avoids the mode-set flicker and gets the framebuffer up before
  # the LUKS passphrase prompt. amdgpu-specific, so it stays out of common —
  # the desktop may well have a different GPU.
  #
  # boot.initrd.luks.devices and boot.resumeDevice are generated by disko from
  # disko.nix, deliberately not repeated here.
  boot.initrd.kernelModules = [ "amdgpu" ];

  # Never change this after install. It is not a version to keep current — it
  # records which stateful-data migrations have already been applied. Per-host
  # on purpose: a desktop installed later gets its own value.
  system.stateVersion = "26.05";
}
