# Host: Lenovo IdeaPad 1 15AMN7 (Ryzen 3 7320U "Mendocino", Radeon 610M,
# 8GB soldered LPDDR5, NVMe).
#
# Known hardware note: this model (82VG/82X5) was one of nine Lenovo AMD
# laptops hit by NVMe IOMMU page faults on suspend/resume. Fixed by DMI
# quirks in Linux 6.6 — unstable is far past that. If suspend ever misbehaves,
# start there rather than blaming NixOS.
{ pkgs, ... }:
{
  imports = [
    ./disko.nix
    ./hardware-configuration.nix
  ];

  networking.hostName = "hutao-laptop";

  boot = {
    # Limine. The ESP is unencrypted and holds kernels + initrd; the initrd
    # unlocks LUKS before mounting root.
    loader = {
      limine = {
        enable = true;
        efiSupport = true;
        # Cap retained boot entries. Root is 90G and /nix/store grows with
        # every generation you keep.
        maxGenerations = 10;
      };
      efi.canTouchEfiVariables = true;
      timeout = 3;
    };

    # boot.initrd.luks.devices and boot.resumeDevice are generated by disko
    # from disko.nix — deliberately not repeated here.

    # Early KMS: avoids the mode-set flicker and gets the framebuffer up
    # before the LUKS passphrase prompt.
    initrd.kernelModules = [ "amdgpu" ];

    # scx needs 6.12+; unstable's default already qualifies, but pin latest
    # so a channel bump can't silently drop below it.
    kernelPackages = pkgs.linuxPackages_latest;
  };

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  # Never change this after install. It is not a version to keep current —
  # it tells NixOS which stateful-data migrations have already been applied.
  system.stateVersion = "25.11";
}
